### ISSUE TITLE
 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by gabrieldylanls** [apryor6/flask_api_example#1]
This code line is returning a None value:

`results = client.get(f'/api/{BASE_ROUTE}', follow_redirects=True).get_json()`

So I can't iterate in:

`            for r in results:
`

Somebody else is getting this error?

**Comment by apryor6** [comment]
What code are you trying to run? As you point out, that error arises when `results` is `None`

**Comment by gabrieldylanls** [comment]
Firstly, I'm sorry for only answer after five days. It was one error in my own code. I forgot to add the routes in my routes.py.
